name = input('BRIDGEKEEPER: Stop.\nWho would cross the Bridge of Death must answer me these questions three.\nBRIDGEKEEPER: What is your name?\n')
quest = input('BRIDGEKEEPER: What is your quest?\n')
color = input('BRIDGEKEEPER: What is your favorite color?\n')

print('----------')
print('Traveler info:')
print(f"Your name is {name}")
print(f"Your quest is {quest}")
print(f"Your favorite color is {color}")
print('----------')
print('BRIDGEKEEPER: Right. Off you go.')
